var art = [
	{name:"Alosaurio", img:"/img/alosaurio.jpg", desc:"Soy un alosaurio", size:3, fam:"Terópodo"},
	{name:"Tiranosaurio", img:"/img/tiranosaurio.jpg", desc:"Soy un tiranosaurio", size:5, fam:"Terópodo"},
	{name:"Triceratops", img:"/img/triceratops.jpg", desc:"En realidad me llamo torosaurio", size:2.5, fam:"Ornitisquia"},
	{name:"Anquilosaurio", img:"/img/anquilosaurio.jpg", desc:"Ráscame la wata", size:2, fam:"Anquilosaurido"},
	{name:"Brontosaurio", img:"/img/brontosaurio.jpg", desc:"Cuello largo", size:15, fam:"Sauropodo"},
	{name:"Paquicefalosaurio", img:"/img/paqui.jpg", desc:"Golpea cosas con la cabeza", size:1, fam:"Ornitisquia"},
	{name:"Velocirraptor", img:"/img/raptor.jpg", desc:"Estoy emparentado con las viejas del metro", size:1, fam:"Terópodo"},
	{name:"Compsognatus", img:"/img/compi.jpg", desc:"Soy chuiquilin", size:0.3, fam:"Terópodo"},
	{name:"", img:"/img/", desc:""},
	{name:"", img:"/img/", desc:""},
	{name:"", img:"/img/", desc:""},
	{name:"", img:"/img/", desc:""},
	{name:"", img:"/img/", desc:""},
	{name:"", img:"/img/", desc:""},
	{name:"", img:"/img/", desc:""},
	{name:"", img:"/img/", desc:""},
	{name:"", img:"/img/", desc:""},
	{name:"", img:"/img/", desc:""},
	{name:"", img:"/img/", desc:""},
	{name:"", img:"/img/", desc:""},
	{name:"", img:"/img/", desc:""},
	{name:"", img:"/img/", desc:""},
	{name:"", img:"/img/", desc:""},
	{name:"", img:"/img/", desc:""},
];
var artleng = art.length;
var x;